image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

  APP_NAME: adventurer
  TAG: $CI_COMMIT_SHA
  REPOSITORY: $DOCKERHUB_ID/$APP_NAME
  IMAGE_NAME: $REPOSITORY:$TAG

stages:
  - build
  - test
  - deploy
  - cleanup

docker_build_and_push:
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - echo $DOCKERHUB_ID
    - docker_build

code_quantity:
  stage: test
  #image:
  variables:
    V1: ok
  allow_failure: true
  script:
    - detect_code_quantity
  only:
    refs:
      - master

.auto_devops: &auto_devops |
  function docker_build()
  {
    echo ci sha $tag
    docker login -u "$DOCKERHUB_ID" -p "$DOCKERHUB_PWD"
    echo $DOCKERHUB_PWD/$appName:$CI_COMMIT_SHA
    docker build -f Dockerfile -t "$IMAGE_NAME" .
  }

  function detect_code_quantity()
  {
    echo code_quantity done
  }

before_script:
  - *auto_devops
