image: docker:latest

variables:
  appName: adventurer
  tag: $CI_COMMIT_SHA
  repository: $dockerhub_id/$appName
  imageName: $repository:$tag

stages:
  - build
  - test
  - deploy
  - cleanup

docker_build_and_push:
  stage: build
  script:
    - docker_build

code_quantity:
  stage: test
  #image:
  variables:
    V1: ok
  allow_failure: true
  script:
    - detect_code_quantity
  only:
    refs:
      - master

.auto_devops: &auto_devops |
  function docker_build()
  {
    docker build -f Dockerfile -t $imageName .
  }

  function detect_code_quantity()
  {
    echo code_quantity done
  }

before_script:
  - docker login -u "$dockerhub_id" -p "#dockerhub_pwd"
  - *auto_devops
