image: alpine:latest


variables:
  POSTGRES_USER: user

stages:
  - build
  - test
  - deploy
  - cleanup

build:
  stage: build
  script:
    - build

code_quantity:
  stage: test
  #image:
  variables:
    V1: ok
  allow_failure: true
  script:
    - detect_code_quantity

.auto_devops: &auto_devops |
  function build()
  {
    echo emm
  }

  function detect_code_quantity()
  {
    echo code_quantity done
  }

before_script:
  - *auto_devops
