system:
  locate: en

db:
  host: 127.0.0.233
  port: 5432
  initialDb: postgres
  username: hahah
  password: this_is_pwd
  max-idle-conn: 10 # 最多的空闲连接数，默认2
  max-open-conn: 10 # 最多的打开连接数，默认0(无限制)
  logmode: true # false的话gorm只会输出错误日志，true会输出详细日志

auth:
  secret: thisissecret!@#
  issuer: adventurer
  audience: fe
  expireMinutes: 120

log:
  prefix: '[adventurer]'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'